"""table notifications

Revision ID: 12ed95fa8f9b
Revises: df2bc9a9befb
Create Date: 2026-09-08 00:02:23.034515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ed95fa8f9b'
down_revision: Union[str, Sequence[str], None] = 'df2bc9a9befb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(notification_type = 'batch_non_compliant' AND batch_id IS NOT NULL AND order_id IS NULL) OR (notification_type = 'order_received' AND order_id IS NOT NULL AND batch_id IS NULL)", name='ck_notification_subject_matches_type'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notifications_warehouse_created', 'notifications', ['warehouse_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_warehouse_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
