"""batches.is_compliant

Revision ID: 3a6297571e74
Revises: 12ed95fa8f9b
Create Date: 2026-09-08 00:07:09.658721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6297571e74'
down_revision: Union[str, Sequence[str], None] = '12ed95fa8f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('is_compliant', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'is_compliant')
    # ### end Alembic commands ###
