"""initial warehouse schema

Revision ID: 91f4b2832351
Revises: 
Create Date: 2026-08-22 12:08:51.159770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f4b2832351'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('country_name', sa.String(length=128), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('nominal_temp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tolerance_temp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nominal_humidity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tolerance_humidity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('country_code')
    )
    op.create_table('farms',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('farm_name', sa.String(length=128), nullable=False),
    sa.Column('farm_ref', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('farm_id'),
    sa.UniqueConstraint('farm_ref')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('odoo_order_id', sa.Integer(), nullable=True),
    sa.Column('order_reference', sa.String(length=64), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_name', sa.String(length=256), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('integration_error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_odoo_order_id'), 'orders', ['odoo_order_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=128), nullable=False),
    sa.Column('warehouse_ref', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('warehouse_id'),
    sa.UniqueConstraint('warehouse_ref')
    )
    op.create_table('batches',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('batch_ref', sa.String(length=64), nullable=False),
    sa.Column('stored_at', sa.Date(), nullable=False),
    sa.Column('shipped_at', sa.Date(), nullable=True),
    sa.Column('quality_grade', sa.String(length=8), nullable=False),
    sa.Column('batch_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.farm_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('batch_id'),
    sa.UniqueConstraint('batch_ref')
    )
    op.create_index('ix_batches_fifo', 'batches', ['warehouse_id', 'stored_at'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('sensor_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('alert_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('uq_alert_active_condition_per_warehouse', 'alerts', ['warehouse_id'], unique=True, postgresql_where=sa.text("alert_status = 'active' AND alert_type = 'condition'"), sqlite_where=sa.text("alert_status = 'active' AND alert_type = 'condition'"))
    op.create_table('measurements',
    sa.Column('measurement_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('meas_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meas_humidity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('meas_temp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], ),
    sa.PrimaryKeyConstraint('measurement_id'),
    sa.UniqueConstraint('sensor_id', 'meas_date', name='uq_measurement_per_sensor')
    )
    op.create_index('ix_measurements_sensor_date', 'measurements', ['sensor_id', 'meas_date'], unique=False)
    op.create_table('order_batches',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('batch_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_batches')
    op.drop_index('ix_measurements_sensor_date', table_name='measurements')
    op.drop_table('measurements')
    op.drop_index('uq_alert_active_condition_per_warehouse', table_name='alerts', postgresql_where=sa.text("alert_status = 'active' AND alert_type = 'condition'"), sqlite_where=sa.text("alert_status = 'active' AND alert_type = 'condition'"))
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('sensors')
    op.drop_table('order_lines')
    op.drop_index('ix_batches_fifo', table_name='batches')
    op.drop_table('batches')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_orders_odoo_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('farms')
    op.drop_table('countries')
    # ### end Alembic commands ###
