"""table sensor_assignments : lien capteur-lot

Revision ID: df2bc9a9befb
Revises: a0a66fe318a0
Create Date: 2026-09-07 21:27:00.214813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2bc9a9befb'
down_revision: Union[str, Sequence[str], None] = 'a0a66fe318a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_assignments',
    sa.Column('sensor_assignment_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], ),
    sa.PrimaryKeyConstraint('sensor_assignment_id')
    )
    op.create_index('ix_sensor_assignments_batch', 'sensor_assignments', ['batch_id', 'assigned_at'], unique=False)
    op.create_index('uq_sensor_assignment_open_per_sensor', 'sensor_assignments', ['sensor_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'), sqlite_where=sa.text('released_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sensor_assignment_open_per_sensor', table_name='sensor_assignments', postgresql_where=sa.text('released_at IS NULL'), sqlite_where=sa.text('released_at IS NULL'))
    op.drop_index('ix_sensor_assignments_batch', table_name='sensor_assignments')
    op.drop_table('sensor_assignments')
    # ### end Alembic commands ###
