[options]
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
dev_mode = True
log_level = info
logfile = False
logrotate = False
workers = 0
max_cron_threads = 1
demo_mode = True
admin_passwd = $pbkdf2-sha512$600000$bu3dm7PWujeG8L73nhNirA$gQEp/aGf57FCannfmKcCyig89D1Q.IeNR0TPz6czmlhzWqr2ft90.ph.aOQV7USOoUQK04M4.E4MypwfgxkIOQ

