apiVersion: v1
kind: Secret
metadata:
  name: {{ include "futurekawa-siege.fullname" . }}-secrets
  labels:
    {{- include "futurekawa-siege.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.siegeApi.jwtSecret | quote }}
  ODOO_ADMIN_PASSWORD: {{ .Values.odoo.adminPassword | quote }}
  ODOO_WEBHOOK_TOKEN: {{ .Values.odoo.webhookToken | quote }}
