@startuml MCD_Warehouse_FutureKawa

!theme plain

title MCD - Base de données entrepôt FutureKawa

entity "Utilisateur" as User {
  * id : UUID <<PK>>
  --
  * email : string
  * password_hash : string
  * role : string
  warehouse_id : UUID <<FK>>
}

entity "Pays" as Country {
  * id : UUID <<PK>>
  --
  * name : string
  * code : string
  * nominal_temp : decimal
  * tolerance_temp : decimal
  * nominal_humidity : decimal
  * tolerance_humidity : decimal
}

entity "Ferme" as Farm {
  * id : UUID <<PK>>
  --
  * country_id : UUID <<FK>>
  * name : string
  * reference : string
}

entity "Entrepôt" as Warehouse {
  * id : UUID <<PK>>
  --
  * country_id : UUID <<FK>>
  * name : string
  * reference : string
}

entity "Lot" as Batch {
  * id : UUID <<PK>>
  --
  * warehouse_id : UUID <<FK>>
  * farm_id : UUID <<FK>>
  * reference : string
  * stored_at : date
  shipped_at : date
  * quality_grade : string
  * status : string
}

entity "Commande" as Order {
  * id : UUID <<PK>>
  --
  odoo_order_id : int
  * order_reference : string
  * order_date : datetime
  * client_name : string
  country_id : UUID <<FK>>
  * status : string
  integration_error_message : string
  * created_at : datetime
  updated_at : datetime
}

entity "LigneCommande" as OrderLine {
  * id : UUID <<PK>>
  --
  * order_id : UUID <<FK>>
  * product_name : string
  * quantity : decimal
}

entity "Capteur" as Sensor {
  * id : UUID <<PK>>
  --
  * warehouse_id : UUID <<FK>>
  * code : string
  * is_active : bool
}

entity "Assignation" as SensorAssignment {
  * id : UUID <<PK>>
  --
  * sensor_id : UUID <<FK>>
  * batch_id : UUID <<FK>>
  * assigned_at : datetime
  released_at : datetime
}

entity "Mesure" as Measurement {
  * id : UUID <<PK>>
  --
  * sensor_id : UUID <<FK>>
  * measured_at : datetime
  * humidity : decimal
  * temperature : decimal
}

entity "Notification" as Notification {
  * id : UUID <<PK>>
  --
  * warehouse_id : UUID <<FK>>
  * type : string
  batch_id : UUID <<FK>>
  order_id : UUID <<FK>>
  * created_at : datetime
  read_at : datetime
}

entity "Alerte" as Alert {
  * id : UUID <<PK>>
  --
  * warehouse_id : UUID <<FK>>
  batch_id : UUID <<FK>>
  * type : string
  * status : string
  * created_at : datetime
  resolved_at : datetime
}

' Relations conceptuelles
Country ||--o{ Farm : "localise"
Country ||--o{ Warehouse : "localise"
Farm ||--o{ Batch : "produit"
Warehouse ||--o{ Batch : "stocke"
Warehouse ||--o{ User : "affecte"
Warehouse ||--o{ Sensor : "surveillé par"
Sensor ||--|{ Measurement : "prend"
Sensor ||--o{ SensorAssignment : "est assigné"
Batch ||--o{ SensorAssignment : "est suivi par"
Warehouse ||--o{ Alert : "lève alerte condition"
Warehouse ||--o{ Notification : "reçoit"
Batch ||--o{ Notification : "motive"
Order ||--o{ Notification : "motive"
Batch ||--o{ Alert : "lève alerte expiration"
Order ||--|{ OrderLine : "contient"
Order }o--o{ Batch : "associe"

@enduml
