@HostAddress = http://localhost:55649

# @name login
POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@futurekawa.com",
  "password": "TestPass123"
}

GET {{HostAddress}}/api/auth/me

GET {{HostAddress}}/api/auth/me
Authorization: Bearer {{login.response.body.$.data.accessToken}}

POST {{HostAddress}}/api/auth/logout
